Repository vidsy/go-kmsconfig, pull requests merged in 2018-10, with the labels that each got.

#26 Allow fields to be omitted using populate method
  Gopkg.lock
  VERSION
  kmsconfig/config.go
  kmsconfig/config_test.go
Labels: Feature, READY

#27 Add time type to the populate method so we can use time values within our config files.
  Gopkg.lock
  VERSION
  kmsconfig/config.go
  kmsconfig/config_test.go
  kmsconfig/fixtures/config/development.json
Labels: Feature, READY

#28 Allow different duration types to specified within config files.
  VERSION
  kmsconfig/config.go
  kmsconfig/config_test.go
  kmsconfig/fixtures/config/development.json
Labels: Bug, READY

#29 Add example config into readme
  README.md
  VERSION
Labels: Enhancement, READY

#30 Update ReadMe and fix struct tag formatting.
  README.md
  VERSION
  kmsconfig/config_test.go
Labels: Bug, READY
